---
title: "MASCARA Playground"
author: "Fred White"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "../")
```

```{r, echo=FALSE}
library(devtools)
library(ggplot2)
library(MetStaT)
library(gASCA)
library(patchwork)
library(readxl)
library(ggfortify)
library(ggrepel)
library(grid)
library(gridExtra)
library(tidyr)
library(tidyverse)
library(reshape2)
library(scales)
library(matrixStats)
library(DESeq2)
library(MASS)
library(glmnet)
library(doParallel)    
library(MUVR) 
library(pheatmap)
library(caret)
library(data.table)
library(plotly)
library(mixOmics)
library(DiscriMiner)
library(pracma)
library(matlib)
library(truncnorm)


source("../DATA_SIM_FUNCS.R")
```

```{r}

meta <- cbind.data.frame(rep(c(1,-1), each = 12), rep(c(1:4), each = 3), rep(c(-1:-4,1:4), each = 3))
colnames(meta) <- c("growth_condition","time","interaction")
meta <- as.data.frame(apply(meta,2,factor))  #9


Experiment_responders <- 30

set.seed(3)
rnd_seed <- abs(rnorm(3, mean = 0.7, sd = 0.5))

sim_data <- Create_Core_DEV_2(nreps = 3, meta = meta, plot = TRUE, 
                        EffectSize = c(X_a_ab = 5, time = 1, E = 10, mu = 1, Struc_E = 1), 
                        struc_resid = TRUE, e_sigma = c(1.5,0.8,0.0), a_sigma = c(1,0.7,0.6,0.1),
                        b_sigma = c(1,0.9), irr_spikes = TRUE, SCORE_SEED = 12, Experiment_responders = Experiment_responders,
                        struc_seed = 127)  
```

```{r}

sim_data <- Create_Core_DEV_2(nreps = 3, meta = meta, 
                        EffectSize = c(X_a_ab = 5, time = 1, E = 1, mu = 1, Struc_E = 0.4),    # E = 10, Struc_E = 1
                        struc_resid = TRUE, e_sigma = c(1.5,0.8,0.0), a_sigma = c(1,0.7,0.6,0.1),
                        b_sigma = c(1,0.9), irr_spikes = TRUE, SCORE_SEED = 12, Experiment_responders = Experiment_responders,
                        struc_seed = 127, score_plot = FALSE, plot = FALSE)  #12

```

```{r}
baits <- paste0("X_",c(1985:1988))   #501:510
spikes <- paste0("X_",c(1989:2000))

ref <- cbind.data.frame(Feature = colnames(sim_data[[1]]), sim_data[[2]], sim_data[[3]])
cols <- colnames(ref[,-1])
ref$Effect <- do.call(paste, c(ref[cols], sep = "_"))
ref$Effect[which(ref$Effect == "0.5_0_0_0.1")] <- "Low PC1"
ref$Effect[which(ref$Effect == "1_0_0_0.1")] <- "Medium PC1"
ref$Effect[which(ref$Effect == "1.5_0_0_0.1")] <- "High PC1"
ref$Effect[which(ref$Effect == "0_0.5_0.1_0")] <- "PC2"
ref$Effect[grep("^0", ref$Effect)] <- "None"
ref$Effect <- factor(ref$Effect, levels = c("Low PC1", "Medium PC1", "High PC1", "PC2", "None"))
colnames(ref)[8] <- "Baits"

ref$Description <- ref$Baits



ref$Baits[1985:1988] <- "Baits"
ref$Baits[1989:2000] <- "Candidates"

ref$Baits[(2000 - (16 + Experiment_responders)):1984] <- "ab1+ve"
# ref$Baits[1969:1976] <- "ab1+ve"
ref$Baits[501:515] <- "ab2+ve"
ref$Baits[486:500] <- "ab2-ve"
# ref$Baits[1969:1976] <- "Expt_Independent"

ref$Baits[1:24] <- "ab1-ve"



ref$Description <- ref$Baits



ar <- ASCA(sim_data[[1]], m = meta, Baits = baits, spikes = spikes, ncands = ncands, distance_calc = FALSE, Return_Model = FALSE)


```

```{r}

gc <- scale(ar[[4]]$decomposition$growth_condition[,1985:1988])  #0.1*
time <- sim_data$Effects[[2]][,1985:1988] #15 * 

int <- scale(sim_data$Effects[[1]][,1985:1988])  #0.08*

ambient <- sim_data$Effects[[4]][,1985:1988]  #1.2 * 
ambient[13:24,] <- 0

noise <- sim_data$Effects[[5]][,1985:1988]  #1.2 * 


rownames(gc) <- paste0("X_",1:nrow(gc))
rownames(time) <- paste0("X_",1:nrow(time))
rownames(int) <- paste0("X_",1:nrow(int))
rownames(ambient) <- paste0("X_",1:nrow(ambient))
rownames(noise) <- paste0("X_",1:nrow(noise))


```

```{r}
max <- max(c(gc,time,int,ambient,noise))
min <- min(c(gc,time,int,ambient,noise))


mData <- reshape2::melt(gc)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p1 <- ggplot(mData, aes(Samples, Features, fill= value)) + 
  geom_tile() +
  ggtitle("Growth Condition") +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())




mData <- reshape2::melt(time)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p2 <- ggplot(mData, aes(Samples, Features, fill= value)) + 
  geom_tile() +
  ggtitle('Time') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())



interaction <- int - time

mData <- reshape2::melt(interaction)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p3 <- ggplot(mData, aes(Samples, Features, fill= value)) + 
  geom_tile() +
  ggtitle('Interaction') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())



mData <- reshape2::melt(ambient)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p4 <- ggplot(mData, aes(Samples, Features, fill= value)) + 
  geom_tile() +
  ggtitle('Ambient') +
  scale_fill_viridis(discrete=FALSE ) +   #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())


mData <- reshape2::melt(noise)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p5 <- ggplot(mData, aes(Samples, Features, fill= value)) + 
  geom_tile() +
  ggtitle('Residuals') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())



data <- (0.1 * interaction) + (1.5*time) + ambient + noise
mData <- reshape2::melt(data)
colnames(mData)[1:2] <- c("Samples","Genes")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p0 <- ggplot(mData, aes(Samples, Genes, fill= value)) + 
  geom_tile() +
  ggtitle('Data') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank())#,
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank())



plots <- list(p1, p2, p3, p4, p5)

p5
```

```{r}
ps <- patchwork::patchworkGrob(wrap_plots(plots) + plot_layout(guides = "collect"))  #, heights = unit(c(5), c("cm")), 
ps1 <- grid.arrange(ps)#, left = "Features", bottom = "Replicate Number                     ")


# p5
```

```{r}

mData <- reshape2::melt(noise + ambient)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p5 <- ggplot(mData, aes(Samples, Features, fill= value)) + 
  geom_tile() +
  ggtitle('Residuals') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

p5
```

```{r}

 
input <- data

```

```{r}


spls_res <- simpls.fit(data.matrix(input[,1:2]), data.matrix(input[,-c(1:2)]), ncomp = 2)

scores <- spls_res$scores

X_P <- spls_res$loadings
Y_P <- spls_res$Yloadings

X_TP <- (spls_res$scores %*% t(spls_res$loadings))
Y_TP <- (spls_res$scores %*% t(spls_res$Yloadings))


X_E <- spls_res$residuals[,1,]
Y_E <- spls_res$residuals[,2,]

```

```{r}
####PLS pattern visualisation change this


data <- scores[]    # data.matrix(sim_data[[4]][,3:4])  #
mData <- reshape2::melt(data)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p0 <- ggplot(mData, aes(Features,Samples, fill= value)) + 
  geom_tile() +
  ggtitle('Patterns (T)') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")



# p0




data <- input[,1:2]
mData <- reshape2::melt(data)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p1 <- ggplot(mData, aes(Samples,Features, fill= value)) + 
  geom_tile() +
  ggtitle('Data; X') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")



data <- input[,3:4]
mData <- reshape2::melt(data)
colnames(mData)[1:2] <- c("Samples","Features")
# mData$Features <- fct_rev(mData$Features)

library(viridis)
library(hrbrthemes)
library(ggplot2)
p2 <- ggplot(mData, aes(Samples,Features, fill= value)) + 
  geom_tile() +
  ggtitle('Data; Y') +
  scale_fill_viridis(discrete=FALSE) +  #, limits = c(min,max)
  theme_bw() +
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")

p0 + (p1 / p2) + theme(legend.position = "none")
```


```{r}
##feature selection alternatives
source("../MASCARA_FUNCS.R")
#default - target projection onto average Q in 2 dimensions
resids <- ar[[3]]


MASCARA_1 <- MASCARA4_test_1(ar[[3]], baits = baits, spikes = spikes)
which(rownames(MASCARA_1[[2]]) %in% spikes)


# # replacing mixomics with SIMPLS from pls package

#1 component, absolute projections
spls_res2.1 <- simpls.fit(resids[,-which(colnames(resids) %in% baits)],
                   resids[,which(colnames(resids) %in% baits)], ncomp = 1)

res_prj <- cbind.data.frame(rownames(spls_res2.1$projection),spls_res2.1$projection)
res_VIP <- res_prj[order(abs(res_prj[,2]), decreasing = TRUE),]
rownames(res_VIP) <- res_VIP[,1]

which(rownames(res_VIP) %in% spikes)


## 2 component target projection
MASCARA_2 <- MASCARA4_test_2(ar[[3]], baits, spikes = spikes)
which(rownames(MASCARA_2[[2]]) %in% spikes)



```

```{r}
resids <- ar[[3]]

spls_res <- spls(resids[,-which(colnames(resids) %in% baits)], 
                 resids[,which(colnames(resids) %in% baits)], all.outputs = TRUE)
  

  

spls_res2 <- simpls.fit(resids[,-which(colnames(resids) %in% baits)],
                resids[,which(colnames(resids) %in% baits)], ncomp = 2)

spls_res2.1 <- simpls.fit(resids[,-which(colnames(resids) %in% baits)],
                   resids[,which(colnames(resids) %in% baits)], ncomp = 1)

res_prj <- cbind.data.frame(rownames(spls_res2.1$projection),spls_res2.1$projection)
res_VIP <- res_prj[order(abs(res_prj[,2]), decreasing = TRUE),]
rownames(res_VIP) <- res_VIP[,1]

which(rownames(res_VIP) %in% spikes)

      

```

```{r}
source("../MASCARA_FUNCS.R")
#classic
MASCARA_2 <- MASCARA4_test_2(ar[[3]], baits, spikes = spikes)
which(rownames(MASCARA_2[[2]]) %in% spikes)

#sr
MASCARA_4 <- MASCARA4_test_7(ar[[3]], baits, spikes = spikes)
which(rownames(MASCARA_4[[2]]) %in% spikes)



#vip
MASCARA_5 <- MASCARA4_test_8(ar[[3]], baits, spikes = spikes)
which(rownames(MASCARA_5[[2]]) %in% spikes)

```

```{r}
#plotting qbar TP for demo

# str(MASCARA_2[[4]])

loadings <- MASCARA_2[[4]]$loadings[]
yloadings <- MASCARA_2[[4]]$Yloadings[]


scores <- MASCARA_2[[4]]$scores[]
colnames(scores) <- gsub(" ","_", colnames(scores))

colnames(loadings) <- gsub(" ","_", colnames(loadings))

line <- colMeans(yloadings)


  
  #adapted from https://stackoverflow.com/questions/1897704/angle-between-two-vectors-in-r
  angle <- function(x,y){
    
    x <- c(as.matrix(x))
    y <- c(as.matrix(y))
    
    dot.prod <- x%*%y 
    norm.x <- norm(x,type="2")
    norm.y <- norm(y,type="2")
    theta <- acos(dot.prod / (norm.x * norm.y))
    return(as.numeric(theta))
  }

  #rotated loadings
  ang <- angle(line,c(1,-0.8))
  
  rot.mat2 <- matrix(c(cos(ang),-sin(ang),sin(ang),cos(ang)),nrow = 2, byrow = TRUE) #clockwise rotation
  
  rotated_point2 <- as.data.frame(c(as.matrix(line)) %*% rot.mat2)
  
  rotate <- function(x,y){
    x <- c(as.matrix(x))
    x %*% y
  }
  
  
  
  loadings_r_baits <- t(apply(loadings,1,rotate, y = rot.mat2))
  
  scores_r_baits <- t(apply(scores,1,rotate, y = rot.mat2))
  
  colnames(loadings_r_baits) <- c("Comp_1","Comp_2")
  colnames(scores_r_baits) <- c("Comp_1","Comp_2")
  

scores_r_baits <- cbind.data.frame(scores_r_baits, meta)

yloadings <- t(apply(yloadings,1,rotate, y = rot.mat2))



```

```{r}
line <- colMeans(yloadings)

LINE <- rbind(line, c(0,0))
LINE <- t(LINE)
colnames(LINE) <- c("to","from")
# scores <- scores %*% 
scores <- cbind.data.frame(scores,meta[,1:2])

a <- ggplot(scores_r_baits, aes(x = Comp_1, y = Comp_2)) +
  geom_point(aes(colour = growth_condition, shape = time, size = 20)) +
  ggtitle("Scores") + 
  theme_bw()

colnames(yloadings) <- colnames(loadings_r_baits)

loadings_r_baits <- rbind(loadings_r_baits, yloadings)
loadings_r_baits <- cbind.data.frame("ID" = rownames(loadings_r_baits), loadings_r_baits)
```


```{r}
loadings_r_baits$ID[-which(loadings_r_baits$ID %in% c(baits,spikes))] <- "Other"

loadings_r_baits$ID[which(loadings_r_baits$ID %in% spikes)] <- "Pathway"
loadings_r_baits$ID[which(loadings_r_baits$ID %in% baits)] <- "Baits"
```

```{r}
b <- ggplot(loadings_r_baits, aes(x = Comp_1, y = Comp_2, colour = ID, shape = ID)) +
  geom_point() +
    ggtitle("Loadings") + 

  geom_segment(x = 0, y = 0, xend = line[1], yend = line[2], lineend = "round", linewidth = 2, colour = "purple", arrow = arrow()) +    
  scale_shape_manual(values=c(3, 16, 17))+


    scale_color_manual(values=c('#E69F00',"black", '#56B4E9'))+
      geom_point(data = loadings_r_baits[which(loadings_r_baits$ID %in% c("Baits","Pathway")),], aes(size = 15)) +
  theme_bw()

b
```

